/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {


    public static void main(String[] args) {
        // Create a bunch of objects that conform to the Cutie interface
        Puppy puppy = new Puppy("Golden");
        Kitty kitty = new Kitty();
        PygmyMarmoset marmoset = new PygmyMarmoset();

        // Create a queue data structure
        var queue = new CutieQueue(10);

        // The size of the queue should equal zero since there are no objects in it
        System.out.println(queue.size());

        // Add the cuties to the queue
        queue.enqueue(puppy);
        queue.enqueue(kitty);
        queue.enqueue(marmoset);

        // The size of the queue should equal three since there are three objects in it
        System.out.println(queue.size());

        // The first dequeue should return the puppy
        queue.dequeue();

        // The second dequeue should return the kitty
        queue.dequeue();

        // The third dequeue should return the pygmy marmoset
        queue.dequeue();
    }
}
